
modLoader="javafml"

loaderVersion="${loader_version_range}"


license="${mod_license}"


[[mods]]
modId="dermantinemod"

version="1.0.0"

displayName="Dermantine Mod"
logoFile="dermantinemodlogo.png"
authors="vladlol"
description='''
my small mod
just for fan and experience

here we have new ore and ore stuff
(it's like iron, but better than diamonds(?))
'''

[[dependencies.${mod_id}]]

modId="forge"

mandatory=true
versionRange="${forge_version_range}"

ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
